const axios = require('axios');
const fs = require('fs-extra');

module.exports.config = {
  name: "4k",
  version: "3.0.0",
  hasPermssion: 0,
  credits: "Ariyan", 
  description: "AI দিয়ে যেকোনো ঘোলা ছবিকে একদম ক্রিস্টাল ক্লিয়ার এবং 4K/8K কোয়ালিটি করুন",
  commandCategory: "Image Editing Tools",
  usages: "ছবির রিপ্লাইয়ে লিখে পাঠান 4k",
  cooldowns: 5,
  dependencies: {
    "axios": "",
    "fs-extra": ""
  }
};

module.exports.handleEvent = async function({ api, event }) {
  const { body, messageReply, threadID, messageID } = event;
  if (body?.toLowerCase().trim() === "4k") {
    if (!messageReply?.attachments?.length || messageReply.attachments[0].type !== "photo")
      return api.sendMessage("📸 বস, ছবি রেসপন্স করতে হবে! যেকোনো ছবির রিপ্লাইয়ে '4k' লিখুন।", threadID, messageID);

    await processImage(api, threadID, messageID, messageReply);
  }
};

module.exports.run = async function({ api, event }) {
  const { threadID, messageID, messageReply } = event;
  if (!messageReply?.attachments?.length || messageReply.attachments[0].type !== "photo")
    return api.sendMessage("📸 যেকোনো ছবির রিপ্লাইয়ে '4k' লিখে কমান্ডটি ব্যবহার করুন!", threadID, messageID);

  await processImage(api, threadID, messageID, messageReply);
};

async function processImage(api, threadID, messageID, messageReply) {
  const cacheDir = __dirname + "/cache";
  const tempPath = cacheDir + `/4k_${Date.now()}.png`;
  const imgUrl = messageReply.attachments[0].url;

  if (!fs.existsSync(cacheDir)) fs.mkdirSync(cacheDir);

  const wait = await api.sendMessage("⏳ একটু অপেক্ষা করুন বস, আপনার ছবিটিকে AI দিয়ে ক্রিস্টাল ক্লিয়ার 4K/8K আল্ট্রা এইচডি করা হচ্ছে...", threadID, messageID);
  api.setMessageReaction("🔮", messageID, (err) => {}, true);

  // ২০২৬ সালের সম্পূর্ণ নতুন এবং সুপার-ফাস্ট ৩টি মাল্টিপল API লুপ
  const apis = [
    `https://api.samirxp.com/api/upscale?url=${encodeURIComponent(imgUrl)}`,
    `https://api.shaurya.xyz/tools/remini?url=${encodeURIComponent(imgUrl)}`,
    `https://joshweb.click/api/remini?url=${encodeURIComponent(imgUrl)}`
  ];

  let success = false;

  for (const url of apis) {
    try {
      // প্রথমে এপিআই থেকে ডাটা রিকোয়েস্ট করা হচ্ছে (JSON ও ফাইল চেক করার জন্য নরমাল রেসপন্স)
      const checkRes = await axios.get(url, { timeout: 30000 });
      let finalDownloadUrl = url;

      // যদি API কোনো JSON লিঙ্ক ব্যাক করে (যেমন: { status: true, result: "https://..." })
      if (checkRes.data && typeof checkRes.data === 'object') {
        finalDownloadUrl = checkRes.data.result || checkRes.data.url || checkRes.data.data;
        if (!finalDownloadUrl) continue; // লিঙ্ক না পেলে পরের এপিআই ট্রাই করবে
      }

      // ফাইনাল ইমেজ ডাউনলোড করা হচ্ছে arraybuffer দিয়ে
      const response = await axios.get(finalDownloadUrl, { responseType: "arraybuffer", timeout: 20000 });
      
      if (response.data && response.data.length > 5000) {
        fs.writeFileSync(tempPath, Buffer.from(response.data));
        success = true;
        break; 
      }
    } catch (e) {
      console.log(`[API FAILED] ওয়ান বাই ওয়ান অটো-সুইচ হচ্ছে...`);
      continue; 
    }
  }

  if (success) {
    try {
      if (wait && wait.messageID) api.unsendMessage(wait.messageID);
      api.setMessageReaction("✅", messageID, (err) => {}, true);

      return api.sendMessage({
        body: "✔️ 4K/8K Enhance Successful! আপনার এইচডি ছবি রেডি বস।\nGenerated by: Ariyan 🤖",
        attachment: fs.createReadStream(tempPath)
      }, threadID, () => {
        if (fs.existsSync(tempPath)) fs.unlinkSync(tempPath);
      }, messageID);
      
    } catch (err) {
      console.error(err);
    }
  } else {
    if (wait && wait.messageID) api.unsendMessage(wait.messageID);
    api.setMessageReaction("❌", messageID, (err) => {}, true);
    return api.sendMessage("❌ দুঃখিত বস, এই মুহূর্তে সবগুলো 4K/8K এআই সার্ভার ওভারলোডেড বা ডাউন আছে। দয়া করে একটু পরে আবার চেষ্টা করুন।", threadID, messageID);
  }
}
