const axios = require('axios');
const fs = require('fs-extra');

module.exports.config = {
  name: "4k",
  version: "2.2.0",
  hasPermssion: 0,
  credits: "Ariyan", 
  description: "AI দিয়ে যেকোনো সাধারণ ঘোলা ছবিকে একদম ক্রিস্টাল ক্লিয়ার এবং 4K কোয়ালিটি করুন (With Auto-Fallback APIs)",
  commandCategory: "Image Editing Tools",
  usages: "ছবির রিপ্লাইয়ে লিখে পাঠান 4k",
  cooldowns: 5,
  dependencies: {
    "axios": "",
    "fs-extra": ""
  }
};

module.exports.handleEvent = async function({ api, event }) {
  const { body, messageReply, threadID, messageID } = event;
  if (body?.toLowerCase().trim() === "4k") {
    if (!messageReply?.attachments?.length || messageReply.attachments[0].type !== "photo")
      return api.sendMessage("📸 বস, ছবি রেসপন্স করতে হবে! যেকোনো ছবির রিপ্লাইয়ে '4k' লিখুন।", threadID, messageID);

    await processImage(api, threadID, messageID, messageReply);
  }
};

module.exports.run = async function({ api, event }) {
  const { threadID, messageID, messageReply } = event;
  if (!messageReply?.attachments?.length || messageReply.attachments[0].type !== "photo")
    return api.sendMessage("📸 যেকোনো ছবির রিপ্লাইয়ে '4k' লিখে কমান্ডটি ব্যবহার করুন!", threadID, messageID);

  await processImage(api, threadID, messageID, messageReply);
};

async function processImage(api, threadID, messageID, messageReply) {
  const cacheDir = __dirname + "/cache";
  const tempPath = cacheDir + `/4k_${Date.now()}.png`;
  const imgUrl = messageReply.attachments[0].url;

  // ক্যাশ ফোল্ডার না থাকলে তৈরি করবে
  if (!fs.existsSync(cacheDir)) fs.mkdirSync(cacheDir);

  // লোডিং মেসেজ এবং রিয়্যাকশন দেওয়া
  const wait = await api.sendMessage("⏳ একটু অপেক্ষা করুন বস, আপনার ছবিটিকে AI দিয়ে 4K আল্ট্রা এইচডি করা হচ্ছে...", threadID, messageID);
  api.setMessageReaction("🔮", messageID, (err) => {}, true);

  // একাধিক ওয়ার্কিং এপিআই লিস্ট (একটিতে সমস্যা হলে অন্যটি কাজ করবে)
  const apis = [
    `https://interstellar-api-0pvy.onrender.com/api/upscale?url=${encodeURIComponent(imgUrl)}`,
    `https://deku-rest-api.xyz/api/remini?url=${encodeURIComponent(imgUrl)}`,
    `https://smfahim.xyz/api/tools/remini?url=${encodeURIComponent(imgUrl)}` // আপনার আগেরটি ব্যাকআপে রাখা হলো
  ];

  let success = false;

  for (const url of apis) {
    try {
      const response = await axios.get(url, { responseType: "arraybuffer", timeout: 25000 }); // ২৫ সেকেন্ড টাইমআউট
      
      // এপিআই যদি ইমেজ ডাটা রিটার্ন করে
      if (response.headers['content-type']?.includes('image') || response.data.length > 1000) {
        fs.writeFileSync(tempPath, Buffer.from(response.data));
        success = true;
        break; // সফল হলে লুপ থেকে বের হয়ে যাবে
      }
    } catch (e) {
      console.log(`API Failed: ${url} - পরবর্তী এপিআই চেষ্টা করা হচ্ছে...`);
      continue; // এই এপিআই ফেইল করলে পরেরটায় যাবে
    }
  }

  if (success) {
    try {
      // লোডিং মেসেজটি ডিলিট করা
      if (wait && wait.messageID) api.unsendMessage(wait.messageID);
      api.setMessageReaction("✅", messageID, (err) => {}, true);

      return api.sendMessage({
        body: "✔️ 4K Enhance Successful! আপনার এইচডি ছবি রেডি বস।\nGenerated by: Ariyan 🤖",
        attachment: fs.createReadStream(tempPath)
      }, threadID, () => {
        if (fs.existsSync(tempPath)) fs.unlinkSync(tempPath);
      }, messageID);
      
    } catch (err) {
      console.error(err);
    }
  } else {
    // সব এপিআই ফেইল করলে এই মেসেজ দেখাবে
    if (wait && wait.messageID) api.unsendMessage(wait.messageID);
    api.setMessageReaction("❌", messageID, (err) => {}, true);
    return api.sendMessage("❌ দুঃখিত বস, এই মুহূর্তে সবগুলো এআই সার্ভার ডাউন আছে। দয়া করে একটু পরে আবার চেষ্টা করুন।", threadID, messageID);
  }
}
