module.exports.config = {
  name: "8k",
  version: "1.0.0",
  hasPermssion: 0,
  credits: "Ariyan",
  description: "এআই (AI) দিয়ে ১০০% হাই-কোয়ালিটি ৮কে ইমেজ তৈরি করুন",
  commandCategory: "utility",
  usages: "8k [আপনার প্রম্পট / আপনি যা আঁকতে চান]",
  cooldowns: 10,
  dependencies: {
    "axios": "",
    "fs-extra": ""
  }
};

module.exports.run = async ({ api, event, args }) => {
  const axios = require('axios');
  const fs = require('fs-extra');
  
  // প্রম্পট চেক করা
  const prompt = args.join(" ");
  if (!prompt) return api.sendMessage("❌ আপনি কী ধরনের ছবি তৈরি করতে চান, তা ইংরেজিতে লিখুন!\n\nযেমন: /8k cyberpunk city, neon lights, 8k resolution, highly detailed", event.threadID, event.messageID);
  
  try {
    // ইউজারকে ওয়েটিং মেসেজ এবং রিয়্যাকশন দেওয়া
    api.sendMessage("⏳ আপনার ৮কে (8K) ইমেজটি তৈরি হচ্ছে, অনুগ্রহ করে একটু অপেক্ষা করুন...", event.threadID, async (err, info) => {
      api.setMessageReaction("🎨", event.messageID, (err) => {}, true);
      
      // ৮কে কোয়ালিটি নিশ্চিত করতে প্রম্পটের সাথে কিছু এক্সট্রা কি-ওয়ার্ড যুক্ত করা
      const finalPrompt = encodeURIComponent(`${prompt}, 8k resolution, photo-realistic, masterpiece, highly detailed, photorealistic, cinematic lighting`);
      
      // Pollinations AI এর স্টেবল ইমেজ জেনারেটর লিঙ্ক
      const imageUrl = `https://image.pollinations.ai/p/${finalPrompt}?width=2048&height=2048&nologo=true&enhance=true`;
      
      const path = __dirname + `/cache/generated_image_${event.senderID}.jpg`;
      
      // ইমেজ বাফার হিসেবে ডাউনলোড করা
      const response = await axios.get(imageUrl, { responseType: 'arraybuffer' });
      fs.writeFileSync(path, Buffer.from(response.data, 'utf-8'));
      
      // গ্রুপে ছবি পাঠানো
      return api.sendMessage({
        body: `✅ এখানে আপনার তৈরি করা ৮কে ইমেজ:\n"${prompt}"\n\nGenerated by: Ariyan 🤖`,
        attachment: fs.createReadStream(path)
      }, event.threadID, () => {
        // ক্যাশ ফাইল ডিলিট করা যেন সার্ভার ডাউন না হয়
        if (fs.existsSync(path)) fs.unlinkSync(path);
      }, event.messageID);
      
    }, event.messageID);

  } catch (err) {
    console.error(err);
    api.sendMessage("❌ দুঃখিত! এই মুহূর্তে ইমেজ জেনারেটরের সার্ভারে সমস্যা হচ্ছে। আবার চেষ্টা করুন।", event.threadID, event.messageID);
    api.setMessageReaction("❌", event.messageID, (err) => {}, true);
  }
};
