const axios = require('axios');
const fs = require('fs-extra');

module.exports.config = {
  name: "8k",
  version: "4.0.0",
  hasPermssion: 0,
  credits: "Ariyan", 
  description: "AI দিয়ে যেকোনো সাধারণ ঘোলা ছবিকে এক চান্সে ক্রিস্টাল ক্লিয়ার এবং 8K কোয়ালিটি করুন",
  commandCategory: "Image Editing Tools",
  usages: "ছবির রিপ্লাইয়ে লিখে পাঠান 8k",
  cooldowns: 4,
  dependencies: {
    "axios": "",
    "fs-extra": ""
  }
};

module.exports.handleEvent = async function({ api, event }) {
  const { body, messageReply, threadID, messageID } = event;
  if (body?.toLowerCase().trim() === "8k" || body?.toLowerCase().trim() === "4k") {
    if (!messageReply?.attachments?.length || messageReply.attachments[0].type !== "photo")
      return api.sendMessage("📸 বস, ছবি রেসপন্স করতে হবে! যেকোনো ছবির রিপ্লাইয়ে '8k' লিখুন।", threadID, messageID);

    await processImage(api, threadID, messageID, messageReply);
  }
};

module.exports.run = async function({ api, event }) {
  const { threadID, messageID, messageReply } = event;
  if (!messageReply?.attachments?.length || messageReply.attachments[0].type !== "photo")
    return api.sendMessage("📸 যেকোনো ছবির রিপ্লাইয়ে '8k' লিখে কমান্ডটি ব্যবহার করুন!", threadID, messageID);

  await processImage(api, threadID, messageID, messageReply);
};

async function processImage(api, threadID, messageID, messageReply) {
  const cacheDir = __dirname + "/cache";
  const tempPath = cacheDir + `/8k_${Date.now()}.png`;
  const imgUrl = messageReply.attachments[0].url;

  if (!fs.existsSync(cacheDir)) fs.mkdirSync(cacheDir);

  const wait = await api.sendMessage("⏳ একটু অপেক্ষা করুন বস, আপনার ছবিটিকে AI দিয়ে এক চান্সে ক্রিস্টাল ক্লিয়ার 8K আল্ট্রা এইচডি করা হচ্ছে...", threadID, messageID);
  api.setMessageReaction("🔮", messageID, (err) => {}, true);

  // ৫টি আলাদা আলাদা হাই-স্পিড এপিআই ব্যাকআপ সার্ভার লুপ
  const apis = [
    `https://api.samirxp.com/api/upscale?url=${encodeURIComponent(imgUrl)}`,
    `https://interstellar-api-0pvy.onrender.com/api/upscale?url=${encodeURIComponent(imgUrl)}`,
    `https://deku-rest-api.xyz/api/remini?url=${encodeURIComponent(imgUrl)}`,
    `https://joshweb.click/api/remini?url=${encodeURIComponent(imgUrl)}`,
    `https://smfahim.xyz/api/tools/remini?url=${encodeURIComponent(imgUrl)}`
  ];

  let success = false;

  for (const url of apis) {
    try {
      // কম সময়ে রেসপন্স না পেলে পরবর্তী এপিআই-তে দ্রুত চলে যাওয়ার জন্য ১৫ সেকেন্ড টাইমআউট
      const checkRes = await axios.get(url, { timeout: 15000 });
      let finalDownloadUrl = url;

      // যদি এপিআই কোনো অবজেক্ট/লিঙ্ক রিটার্ন করে তা ডিটেক্ট করা
      if (checkRes.data && typeof checkRes.data === 'object') {
        finalDownloadUrl = checkRes.data.result || checkRes.data.url || checkRes.data.data || checkRes.data.image_url;
        if (!finalDownloadUrl) continue;
      }

      // ফাইনাল ডাটা ডাউনলোড
      const response = await axios.get(finalDownloadUrl, { responseType: "arraybuffer", timeout: 15000 });
      
      if (response.data && response.data.length > 5000) {
        fs.writeFileSync(tempPath, Buffer.from(response.data));
        success = true;
        break; // একটি সফল হলে লুপ বন্ধ করে দেবে
      }
    } catch (e) {
      console.log(`[SERVER FAIL] Switching to backup server...`);
      continue; // সার্ভার ডাউন থাকলে পরের সার্ভারে জাম্প করবে
    }
  }

  if (success) {
    try {
      if (wait && wait.messageID) api.unsendMessage(wait.messageID);
      api.setMessageReaction("✅", messageID, (err) => {}, true);

      return api.sendMessage({
        body: "✔️ 8K Ultra HD Enhance Successful! আপনার ক্রিস্টাল ক্লিয়ার ছবি রেডি বস।\nGenerated by: Ariyan 🤖",
        attachment: fs.createReadStream(tempPath)
      }, threadID, () => {
        if (fs.existsSync(tempPath)) fs.unlinkSync(tempPath);
      }, messageID);
      
    } catch (err) {
      console.error(err);
    }
  } else {
    if (wait && wait.messageID) api.unsendMessage(wait.messageID);
    api.setMessageReaction("❌", messageID, (err) => {}, true);
    return api.sendMessage("❌ দুঃখিত বস, এই মুহূর্তে সবগুলো এআই সার্ভার ওভারলোডেড আছে। দয়া করে কিছুক্ষণ পর আবার চেষ্টা করুন।", threadID, messageID);
  }
}
