const axios = require('axios');
const fs = require('fs-extra');

module.exports.config = {
  name: "8k",
  version: "2.1.0",
  hasPermssion: 0,
  credits: "Ariyan", 
  description: "ছবির রিপ্লাইয়ে '8k' লিখলে বা কমান্ড দিলে এআই দিয়ে ছবিকে আল্ট্রা এইচডি ৮কে কোয়ালিটি করে",
  commandCategory: "Image Editing Tools",
  usages: "ছবির রিপ্লাইয়ে লিখে পাঠান 8k",
  cooldowns: 5,
  dependencies: {
    "axios": "",
    "fs-extra": ""
  }
};

module.exports.handleEvent = async function({ api, event }) {
  const { body, messageReply, threadID, messageID } = event;
  // গ্রুপে কেউ ছবির রিপ্লাইয়ে শুধু '8k' লিখলে এটি ট্রিগার হবে
  if (body?.toLowerCase().trim() === "8k") {
    if (!messageReply?.attachments?.length || messageReply.attachments[0].type !== "photo")
      return api.sendMessage("📸 বস, ছবি রেসপন্স করতে হবে! যেকোনো ছবির রিপ্লাইয়ে '8k' লিখুন।", threadID, messageID);

    await process8kImage(api, threadID, messageID, messageReply);
  }
};

module.exports.run = async function({ api, event }) {
  const { threadID, messageID, messageReply } = event;
  // কেউ প্রিফিক্স দিয়ে কমান্ড ব্যবহার করলে
  if (!messageReply?.attachments?.length || messageReply.attachments[0].type !== "photo")
    return api.sendMessage("📸 যেকোনো ছবির রিপ্লাইয়ে '8k' লিখে কমান্ডটি ব্যবহার করুন!", threadID, messageID);

  await process8kImage(api, threadID, messageID, messageReply);
};

async function process8kImage(api, threadID, messageID, messageReply) {
  const cacheDir = __dirname + "/cache";
  const tempPath = cacheDir + `/8k_${Date.now()}.png`;
  const imgUrl = messageReply.attachments[0].url;

  if (!fs.existsSync(cacheDir)) fs.mkdirSync(cacheDir);

  // লোডিং মেসেজ ও রিয়্যাকশন
  const wait = await api.sendMessage("⏳ একটু অপেক্ষা করুন বস, আপনার ছবিটিকে AI দিয়ে 8K আল্ট্রা এইচডি করা হচ্ছে...", threadID, messageID);
  api.setMessageReaction("🎨", messageID, (err) => {}, true);

  try {
    // ইমেজ এনহ্যান্স করে সুপার রেজুলেশন দেওয়ার জন্য হাই-কোয়ালিটি এপিআই
    const enhanceUrl = `https://smfahim.xyz/api/tools/remini?url=${encodeURIComponent(imgUrl)}`;
    
    const response = await axios.get(enhanceUrl, { responseType: "arraybuffer" });
    fs.writeFileSync(tempPath, Buffer.from(response.data));

    // সাকসেস হলে লোডিং মেসেজ আনসেন্ড করা
    api.unsendMessage(wait.messageID);
    api.setMessageReaction("✅", messageID, (err) => {}, true);

    return api.sendMessage({
      body: "✔️ 8K Ultra HD Enhance Successful! আপনার হাই-রেজুলেশন ছবি রেডি বস।\nGenerated by: Ariyan 🤖",
      attachment: fs.createReadStream(tempPath)
    }, threadID, () => {
      if (fs.existsSync(tempPath)) fs.unlinkSync(tempPath);
    }, messageID);

  } catch (e) {
    console.error(e);
    if(wait && wait.messageID) api.unsendMessage(wait.messageID);
    api.setMessageReaction("❌", messageID, (err) => {}, true);
    return api.sendMessage("❌ দুঃখিত বস, সার্ভার ডাউন থাকার কারণে এই মুহূর্তে ছবিটি 8K করা যায়নি। দয়া করে একটু পরে আবার চেষ্টা করুন।", threadID, messageID);
  }
}
