const axios = require('axios');
const fs = require('fs-extra');

module.exports.config = {
  name: "edit",
  version: "1.0.0",
  hasPermssion: 0,
  credits: "Ariyan", 
  description: "AI দিয়ে যেকোনো ছবিকে এক ক্লিকে ব্যাকগ্রাউন্ড রিমুভ, এনিমে, কালারাইজ বা স্কেচ করুন",
  commandCategory: "Image Editing Tools",
  usages: "ছবির রিপ্লাইয়ে লিখুন: edit bg / anime / color / sketch",
  cooldowns: 5,
  dependencies: {
    "axios": "",
    "fs-extra": ""
  }
};

module.exports.handleEvent = async function({ api, event }) {
  const { body, messageReply, threadID, messageID } = event;
  if (body?.toLowerCase().startsWith("edit")) {
    if (!messageReply?.attachments?.length || messageReply.attachments[0].type !== "photo")
      return api.sendMessage("📸 বস, যেকোনো ছবির রিপ্লাইয়ে টাইপ করুন:\n\n» edit bg (ব্যাকগ্রাউন্ড রিমুভ)\n» edit anime (কার্টুন স্টাইল)\n» edit color (সাদাকালো রঙিন করা)\n» edit sketch (পেন্সিল ড্রয়িং)", threadID, messageID);

    await processImage(api, threadID, messageID, messageReply, body);
  }
};

module.exports.run = async function({ api, event }) {
  const { body, threadID, messageID, messageReply } = event;
  if (!messageReply?.attachments?.length || messageReply.attachments[0].type !== "photo")
    return api.sendMessage("📸 যেকোনো ছবির রিপ্লাইয়ে টাইপ করুন:\n\n» edit bg (ব্যাকগ্রাউন্ড রিমুভ)\n» edit anime (কার্টুন স্টাইল)\n» edit color (সাদাকালো রঙিন করা)\n» edit sketch (পেন্সিল ড্রয়িং)", threadID, messageID);

  await processImage(api, threadID, messageID, messageReply, body);
};

async function processImage(api, threadID, messageID, messageReply, body) {
  const cacheDir = __dirname + "/cache";
  const tempPath = cacheDir + `/edit_${Date.now()}.png`;
  const imgUrl = messageReply.attachments[0].url;

  if (!fs.existsSync(cacheDir)) fs.mkdirSync(cacheDir);

  // ব্যবহারকারীর ইনপুট চেক করা
  const args = body.toLowerCase().split(" ");
  const type = args[1]; // bg, anime, color, sketch

  let actionText = "";
  let apiPaths = [];

  // টাইপ অনুযায়ী এপিআই এবং টেক্সট সিলেক্ট করা
  if (type === "bg" || type === "removebg") {
    actionText = "ব্যাকগ্রাউন্ড রিমুভ";
    apiPaths = [
      `https://api.samirxp.com/api/removebg?url=${encodeURIComponent(imgUrl)}`,
      `https://deku-rest-api.xyz/api/removebg?url=${encodeURIComponent(imgUrl)}`
    ];
  } else if (type === "anime" || type === "cartoon") {
    actionText = "এনিমে কার্টুন ফিল্টার";
    apiPaths = [
      `https://api.samirxp.com/api/toanime?url=${encodeURIComponent(imgUrl)}`,
      `https://joshweb.click/api/toanime?url=${encodeURIComponent(imgUrl)}`
    ];
  } else if (type === "color" || type === "colorize") {
    actionText = "কালারাইজ বা রঙিন";
    apiPaths = [
      `https://api.samirxp.com/api/colorize?url=${encodeURIComponent(imgUrl)}`,
      `https://deku-rest-api.xyz/api/colorize?url=${encodeURIComponent(imgUrl)}`
    ];
  } else if (type === "sketch" || type === "draw") {
    actionText = "পেন্সিল স্কেচ আর্ট";
    apiPaths = [
      `https://api.samirxp.com/api/sketch?url=${encodeURIComponent(imgUrl)}`,
      `https://joshweb.click/api/sketch?url=${encodeURIComponent(imgUrl)}`
    ];
  } else {
    return api.sendMessage("❌ ভুল কমান্ড বস! ছবির রিপ্লাইয়ে শুধু নিচের যেকোনো একটি লিখুন:\n\n» edit bg\n» edit anime\n» edit color\n» edit sketch", threadID, messageID);
  }

  const wait = await api.sendMessage(`⏳ একটু অপেক্ষা করুন বস, AI দিয়ে আপনার ছবিটি ${actionText} করা হচ্ছে...`, threadID, messageID);
  api.setMessageReaction("🎨", messageID, (err) => {}, true);

  let success = false;

  // মাল্টিপল ব্যাকআপ এপিআই লুপ
  for (const url of apiPaths) {
    try {
      const checkRes = await axios.get(url, { timeout: 20000 });
      let finalDownloadUrl = url;

      if (checkRes.data && typeof checkRes.data === 'object') {
        finalDownloadUrl = checkRes.data.result || checkRes.data.url || checkRes.data.data || checkRes.data.image_url;
        if (!finalDownloadUrl) continue;
      }

      const response = await axios.get(finalDownloadUrl, { responseType: "arraybuffer", timeout: 20000 });
      
      if (response.data && response.data.length > 5000) {
        fs.writeFileSync(tempPath, Buffer.from(response.data));
        success = true;
        break;
      }
    } catch (e) {
      console.log(`[EDIT API FAIL] Switching to next backup server...`);
      continue;
    }
  }

  if (success) {
    try {
      if (wait && wait.messageID) api.unsendMessage(wait.messageID);
      api.setMessageReaction("✅", messageID, (err) => {}, true);

      return api.sendMessage({
        body: `✔️ Photo Editing Successful! আপনার ${actionText} করা ছবি রেডি বস।\nGenerated by: Ariyan 🤖`,
        attachment: fs.createReadStream(tempPath)
      }, threadID, () => {
        if (fs.existsSync(tempPath)) fs.unlinkSync(tempPath);
      }, messageID);
      
    } catch (err) {
      console.error(err);
    }
  } else {
    if (wait && wait.messageID) api.unsendMessage(wait.messageID);
    api.setMessageReaction("❌", messageID, (err) => {}, true);
    return api.sendMessage("❌ দুঃখিত বস, এডিটিং সার্ভারগুলো এই মুহূর্তে ডাউন আছে। দয়া করে একটু পর আবার চেষ্টা করুন।", threadID, messageID);
  }
}
