const axios = require('axios');
const fs = require('fs-extra');

module.exports.config = {
  name: "idol",
  version: "3.0.0",
  hasPermssion: 0,
  credits: "Ariyan",
  description: "Idol বা Goat লিখলে চোখের পলকে ফানি ভিডিও রিপ্লাই করবে",
  commandCategory: "fun",
  usages: "গ্রুপে 'idol' অথবা 'goat' লিখুন",
  cooldowns: 1,
  dependencies: {
    "axios": "",
    "fs-extra": ""
  }
};

module.exports.handleEvent = async function({ api, event }) {
  const { body, threadID, messageID, senderID } = event;
  if (!body) return;

  const text = body.toLowerCase().trim();

  // যদি মেসেজে 'idol' অথবা 'goat' থাকে
  if (text === "idol" || text === "goat") {
    
    // 📥 [ফিক্সড ভিডিও লিঙ্ক] এই এপিআই লিঙ্কটি রেন্ডার সার্ভারের জন্য ১০০% অপ্টিমাইজড
    const videoUrl = "https://smfahim.xyz/api/tools/goat.mp4"; 
    const path = __dirname + `/cache/goat_final_${senderID}_${Date.now()}.mp4`;

    // লোডিং রিয়্যাকশন দেওয়া
    api.setMessageReaction("🐐", messageID, (err) => {}, true);

    try {
      // ভিডিও ডাটা বাফার হিসেবে নেওয়া
      const response = await axios.get(videoUrl, { responseType: "arraybuffer" });
      fs.writeFileSync(path, Buffer.from(response.data));

      // গ্রুপে ভিডিও পাঠানো
      return api.sendMessage({
        body: `Here is your GOAT/IDOL video! 👑🔥\nGenerated by: Ariyan 🤖`,
        attachment: fs.createReadStream(path)
      }, threadID, () => {
        // ক্যাশ ফাইল ডিলিট করা যেন রেন্ডারের মেমোরি জ্যাম না হয়
        if (fs.existsSync(path)) fs.unlinkSync(path);
      }, messageID);

    } catch (err) {
      console.error(err);
      api.setMessageReaction("❌", messageID, (err) => {}, true);
      return api.sendMessage("❌ দুঃখিত বস, ফেসবুক বা সার্ভার নেটওয়ার্কের কারণে ভিডিওটি পাঠানো যাচ্ছে না। আবার চেষ্টা করুন।", threadID, messageID);
    }
  }
};

module.exports.run = async function({ api, event }) {
  return api.sendMessage("💡 এই কমান্ডটি ব্যবহার করতে গ্রুপে সরাসরি 'idol' অথবা 'goat' লিখুন!", event.threadID, event.messageID);
};
