const axios = require('axios');
const fs = require('fs-extra');

module.exports.config = {
  name: "idol",
  version: "1.0.1",
  hasPermssion: 0,
  credits: "Ariyan",
  description: "Idol ba Goat likhle automatic uploaded video reply korbe",
  commandCategory: "fun",
  usages: "Group-e 'idol' othoba 'goat' likhun",
  cooldowns: 3,
  dependencies: {
    "axios": "",
    "fs-extra": ""
  }
};

module.exports.handleEvent = async function({ api, event }) {
  const { body, threadID, messageID } = event;
  if (!body) return;

  const text = body.toLowerCase().trim();

  // Jodi message-e 'idol' othoba 'goat' thake
  if (text === "idol" || text === "goat") {
    
    // 📥 Niche apnar upload kora video-r select kora direct link bosan
    const videoLinks = [
      "https://your-uploaded-video-link.mp4", // 👈 Ekhane video-r direct link-ti bosaben
      "https://your-video-link-2.mp4",
      "https://your-video-link-3.mp4"
    ];

    // Randomly ekti link select kora
    const randomVideo = videoLinks[Math.floor(Math.random() * videoLinks.length)];
    const path = __dirname + `/cache/idol_${Date.now()}.mp4`;

    api.setMessageReaction("🐐", messageID, (err) => {}, true);

    try {
      // Video buffer download kora
      const response = await axios.get(randomVideo, { responseType: "arraybuffer" });
      fs.writeFileSync(path, Buffer.from(response.data));

      // Group-e video pathano
      return api.sendMessage({
        body: `Here is your GOAT/IDOL video! 👑🔥\nGenerated by: Ariyan`,
        attachment: fs.createReadStream(path)
      }, threadID, () => {
        // Cache file delete kora hocche jate server crash na khay
        if (fs.existsSync(path)) fs.unlinkSync(path);
      }, messageID);

    } catch (err) {
      console.error(err);
      return api.sendMessage("❌ Video-ti load korte somossa hocche boss! Link check korun.", threadID, messageID);
    }
  }
};

module.exports.run = async function({ api, event }) {
  return api.sendMessage("💡 Ei command-ti use korte group-e sorasori 'idol' othoba 'goat' likhun!", event.threadID, event.messageID);
};
